# Generated by Django 5.2.7 on 2026-09-15 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('recording_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RECORDING', 'Recording'), ('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('READY_FOR_REVIEW', 'Ready For Review'), ('IN_REVIEW', 'In Review'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRY', 'Retry')], default='CREATED', max_length=20, verbose_name='Status')),
                ('gps_latitude', models.FloatField(blank=True, null=True, verbose_name='GPS Latitude')),
                ('gps_longitude', models.FloatField(blank=True, null=True, verbose_name='GPS Longitude')),
                ('gps_captured_at', models.DateTimeField(blank=True, null=True, verbose_name='GPS Captured At')),
                ('road_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Road Name')),
                ('police_station_jurisdiction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Police Station Jurisdiction')),
                ('case_fir_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Case / FIR Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recordings', to=settings.AUTH_USER_MODEL, verbose_name='Officer')),
            ],
            options={
                'db_table': 'recordings',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('audio_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('LIVE', 'Live Recording'), ('UPLOAD', 'File Upload')], max_length=10, verbose_name='Source')),
                ('storage_path', models.CharField(max_length=500, verbose_name='Storage Path')),
                ('content_type', models.CharField(max_length=100, verbose_name='Content Type')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Duration Seconds')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='File Size Bytes')),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True, verbose_name='Checksum SHA-256')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='audio', to='recordings.recording', verbose_name='Recording')),
            ],
            options={
                'db_table': 'recording_audio',
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('ORIGINAL', 'Original Language'), ('ENGLISH', 'English')], max_length=10, verbose_name='Language')),
                ('text', models.TextField(verbose_name='Text')),
                ('detected_language_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Detected Language Code')),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provider Name')),
                ('provider_metadata', models.JSONField(blank=True, default=dict, verbose_name='Provider Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcripts', to='recordings.recording', verbose_name='Recording')),
            ],
            options={
                'db_table': 'recording_transcripts',
                'unique_together': {('recording', 'language')},
            },
        ),
    ]
