# Generated by Django 5.2.7 on 2026-09-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Original Filename'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='checksum_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Checksum SHA-256'),
        ),
    ]
