# Generated by Django 5.2.7 on 2026-09-25 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_audio_original_filename_alter_audio_checksum_sha256'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transcript',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='audio',
            name='role',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('SUPPLEMENTAL', 'Supplemental')], default='ORIGINAL', max_length=15, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transcripts', to='recordings.audio', verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audios', to='recordings.recording', verbose_name='Recording'),
        ),
        migrations.AlterUniqueTogether(
            name='transcript',
            unique_together={('audio', 'language')},
        ),
    ]
