# Generated by Django 5.2.7 on 2026-09-28 15:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_alter_transcript_unique_together_audio_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('voice_session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Voice Session ID')),
                ('room_name', models.CharField(max_length=255, unique=True, verbose_name='Room Name')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('INCOMPLETE', 'Incomplete')], default='CREATED', max_length=15, verbose_name='Status')),
                ('transcript_original', models.TextField(blank=True, default='', verbose_name='Original Transcript')),
                ('transcript_english', models.TextField(blank=True, default='', verbose_name='English Transcript')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_sessions', to='recordings.recording', verbose_name='Recording')),
            ],
            options={
                'db_table': 'voice_sessions',
            },
        ),
    ]
