# Generated by Django 5.2.7 on 2026-09-30 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_voicesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicesession',
            name='room_name',
        ),
    ]
