# Generated by Django 5.2.7 on 2026-09-15 11:06

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField()),
                ('action', models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], max_length=10)),
                ('model', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=10)),
                ('end_point', models.CharField(max_length=125)),
                ('details', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_log',
                'ordering': ['-created_on'],
            },
        ),
    ]
