# Generated by Django 5.2.7 on 2026-09-15 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('STT', 'Speech To Text'), ('TRANSLATION', 'Translation'), ('EXTRACTION', 'eDAR Extraction'), ('EXPORT', 'Export')], max_length=20, verbose_name='Job Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=10, verbose_name='Status')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Attempt Count')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Max Attempts')),
                ('is_retryable', models.BooleanField(blank=True, null=True, verbose_name='Is Retryable')),
                ('error_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Error Code')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provider Name')),
                ('provider_metadata', models.JSONField(blank=True, default=dict, verbose_name='Provider Metadata')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_jobs', to='recordings.recording', verbose_name='Recording')),
            ],
            options={
                'db_table': 'processing_jobs',
            },
        ),
        migrations.CreateModel(
            name='ProcessingEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100, verbose_name='Event Type')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='Occurred At')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_events', to='recordings.recording', verbose_name='Recording')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='processing.processingjob', verbose_name='Processing Job')),
            ],
            options={
                'db_table': 'processing_events',
                'ordering': ['occurred_at'],
            },
        ),
    ]
