# Generated by Django 5.2.7 on 2026-09-25 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
        ('recordings', '0003_alter_transcript_unique_together_audio_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='recordings.audio', verbose_name='Audio'),
        ),
    ]
