# Generated by Django 5.2.7 on 2026-09-15 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recordings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EdarRecord',
            fields=[
                ('edar_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved')], default='PENDING_REVIEW', max_length=20, verbose_name='Review Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='edar_record', to='recordings.recording', verbose_name='Recording')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'db_table': 'edar_records',
            },
        ),
        migrations.CreateModel(
            name='EdarFieldValue',
            fields=[
                ('field_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=100, verbose_name='Field Key')),
                ('layer', models.CharField(choices=[('AI', 'AI Extracted'), ('APPROVED', 'Officer Approved')], max_length=10, verbose_name='Layer')),
                ('known', models.CharField(choices=[('KNOWN', 'Known'), ('UNKNOWN', 'Unknown'), ('NOT_APPLICABLE', 'Not Applicable'), ('UNCERTAIN', 'Uncertain')], default='KNOWN', max_length=20, verbose_name='Known')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='Value')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='Confidence')),
                ('source_transcript_segment', models.TextField(blank=True, null=True, verbose_name='Source Transcript Segment')),
                ('source_start_time', models.FloatField(blank=True, null=True, verbose_name='Source Start Time')),
                ('source_end_time', models.FloatField(blank=True, null=True, verbose_name='Source End Time')),
                ('extraction_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Extraction Version')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('edar_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_values', to='edar.edarrecord', verbose_name='eDAR Record')),
            ],
            options={
                'db_table': 'edar_field_values',
                'unique_together': {('edar_record', 'field_key', 'layer')},
            },
        ),
    ]
