# Generated by Django 5.2.7 on 2026-09-20 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edar', '0001_initial'),
        ('processing', '0001_initial'),
        ('recordings', '0002_audio_original_filename_alter_audio_checksum_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='edarrecord',
            name='extracted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Extracted At'),
        ),
        migrations.AddField(
            model_name='edarrecord',
            name='extraction_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='processing.processingjob', verbose_name='Extraction Job'),
        ),
        migrations.AddField(
            model_name='edarrecord',
            name='quality_report',
            field=models.JSONField(blank=True, default=dict, verbose_name='Quality Report'),
        ),
        migrations.AddField(
            model_name='edarrecord',
            name='quality_status',
            field=models.CharField(blank=True, choices=[('VALIDATED', 'Validated'), ('VALIDATION_WARNING', 'Validation Warning')], max_length=20, null=True, verbose_name='Quality Status'),
        ),
        migrations.AddField(
            model_name='edarrecord',
            name='source_transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='recordings.transcript', verbose_name='Source Transcript'),
        ),
    ]
